/*
Timeweb Cloud API

Testing SnapshotsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SnapshotsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SnapshotsAPIService CommitRestorePoint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vdsId int32

		httpRes, err := apiClient.SnapshotsAPI.CommitRestorePoint(context.Background(), vdsId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnapshotsAPIService CreateRestorePoint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vdsId int32

		resp, httpRes, err := apiClient.SnapshotsAPI.CreateRestorePoint(context.Background(), vdsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnapshotsAPIService GetRestorePoint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vdsId int32

		resp, httpRes, err := apiClient.SnapshotsAPI.GetRestorePoint(context.Background(), vdsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnapshotsAPIService GetRestorePoints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SnapshotsAPI.GetRestorePoints(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnapshotsAPIService RollbackRestorePoint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vdsId int32

		httpRes, err := apiClient.SnapshotsAPI.RollbackRestorePoint(context.Background(), vdsId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
