/*
Timeweb Cloud API

Testing ContainerRegistryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ContainerRegistryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContainerRegistryAPIService CreateRegistry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContainerRegistryAPI.CreateRegistry(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService DeleteRegistry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var registryId int32

		httpRes, err := apiClient.ContainerRegistryAPI.DeleteRegistry(context.Background(), registryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService GetRegistries", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContainerRegistryAPI.GetRegistries(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService GetRegistry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var registryId int32

		resp, httpRes, err := apiClient.ContainerRegistryAPI.GetRegistry(context.Background(), registryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService GetRegistryPresets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContainerRegistryAPI.GetRegistryPresets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService GetRegistryRepositories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var registryId int32

		resp, httpRes, err := apiClient.ContainerRegistryAPI.GetRegistryRepositories(context.Background(), registryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerRegistryAPIService UpdateRegistry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var registryId int32

		resp, httpRes, err := apiClient.ContainerRegistryAPI.UpdateRegistry(context.Background(), registryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
