/*
Timeweb Cloud API

Testing RoutersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_RoutersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RoutersAPIService AddNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.AddNetworks(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService CreateRouter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RoutersAPI.CreateRouter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService DeleteDnat", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var dnatId string

		httpRes, err := apiClient.RoutersAPI.DeleteDnat(context.Background(), routerId, dnatId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService DeleteRouter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		httpRes, err := apiClient.RoutersAPI.DeleteRouter(context.Background(), routerId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService DeleteRouterNat", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var networkName string

		resp, httpRes, err := apiClient.RoutersAPI.DeleteRouterNat(context.Background(), routerId, networkName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService DeleteRouterNetwork", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var networkName string

		httpRes, err := apiClient.RoutersAPI.DeleteRouterNetwork(context.Background(), routerId, networkName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService DeleteStaticRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var staticRouteId string

		httpRes, err := apiClient.RoutersAPI.DeleteStaticRoute(context.Background(), routerId, staticRouteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetAvailableStaticRoutes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.GetAvailableStaticRoutes(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetDnat", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.GetDnat(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetDnatRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var dnatId string

		resp, httpRes, err := apiClient.RoutersAPI.GetDnatRule(context.Background(), routerId, dnatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.GetNetworks(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetRouter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.GetRouter(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetRouterAvailableNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RoutersAPI.GetRouterAvailableNetworks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetRouterPresets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RoutersAPI.GetRouterPresets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetRouterStatistics", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var timeFrom string
		var period string
		var keys string

		resp, httpRes, err := apiClient.RoutersAPI.GetRouterStatistics(context.Background(), routerId, timeFrom, period, keys).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetRouters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RoutersAPI.GetRouters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService GetStaticRoutes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.GetStaticRoutes(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService PatchNetwork", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var networkName string

		resp, httpRes, err := apiClient.RoutersAPI.PatchNetwork(context.Background(), routerId, networkName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService PatchNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.PatchNetworks(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService PostDnat", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.PostDnat(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService PostStaticRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.PostStaticRoute(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService UpdateRouter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string

		resp, httpRes, err := apiClient.RoutersAPI.UpdateRouter(context.Background(), routerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoutersAPIService UpdateRouterNat", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routerId string
		var networkName string

		resp, httpRes, err := apiClient.RoutersAPI.UpdateRouterNat(context.Background(), routerId, networkName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
